# Woodpecker CI pipeline for React app

steps:
  install:
    image: node:18
    commands:
      - npm ci
    when:
      event:
        - push
        - pull_request
  lint:
    image: node:18
    commands:
      - npm run lint || echo "No lint script defined"
    when:
      event:
        - push
        - pull_request
  test:
    image: node:18
    commands:
      - npm test -- --watchAll=false
    when:
      event:
        - push
        - pull_request
  build:
    image: node:18
    commands:
      - npm run build
    when:
      event:
        - push
        - pull_request
